apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-parser-deployment
  labels:
    app: ingredient-parser
spec:
  selector:
    matchLabels:
      app: ingredient-parser
      role: web
  template:
    metadata:
      labels:
        app: ingredient-parser
        role: web
    spec:
      containers:
      - image: registry.openculinary.org/reciperadar/ingredient-parser
        imagePullPolicy: IfNotPresent
        name: ingredient-parser
        ports:
        - containerPort: 8000
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/tmp
          name: var-tmp
      volumes:
      - name: var-tmp
        emptyDir:
          medium: "Memory"
          sizeLimit: "128Mi"
